# Generated by Django 4.2.21 on 2025-05-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_date', models.DateField()),
                ('week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('weekday_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DimHoliday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_flag', models.BooleanField()),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
                ('holiday_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimRegion',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimSalesChannel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimStore',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('store_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FactSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimsaleschannel')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimdate')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimholiday')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimregion')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.dimstore')),
            ],
        ),
    ]
